---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - loki_url is defined
      - ofelia_config_path is defined

- name: Create the dockernetwork
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  docker_container:
    name: "{{ application_name }}-app"
    image: "mcuadros/ofelia:latest"
    restart_policy: "always"
    cleanup: true
    pull: true
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}ofelia:/etc/ofelia"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: "{{ docker_network_name }}"

- name: Copy ofelia config
  copy:
    src: "{{ ofelia_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}ofelia/config.ini"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

# Restart the container so the configuration changes are picked up
- name: Restart ofelia
  command: docker restart ofelia-app
  register: restart_ofelia_result
  changed_when: restart_ofelia_result.rc != 0
