---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - docker_network_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - ofelia_config_path is defined

- name: Create the dockernetwork
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  docker_container:
    name: "{{ application_name }}-app"
    image: "mcuadros/ofelia:latest"
    restart_policy: "always"
    cleanup: true
    pull: true
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}-app"
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}ofelia:/etc/ofelia"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: "{{ docker_network_name }}"

# TODO: When the config changes the container needs to be restarted manually
- name: Copy ofelia config
  copy:
    src: "{{ ofelia_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}ofelia/config.ini"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
